# Generated by Django 3.0.3 on 2020-12-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201223_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
